project_id = "egzwkyqpkexgrhbxwcvb"

[functions.enviar-contato]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.raiox-mensal-cron]
verify_jwt = false

[functions.ig-webhook]
verify_jwt = false
