// Pesquisa de precificação da Pólia — externa (coletada fora do site, formato
// Van Westendorp) e importada aqui só pra virar gráfico no admin. Perguntas e
// rótulos espelham exatamente o formulário original, pra importação bater
// 1:1 sem perda de dado.
//
// Pesquisa separada da discovery-negocio: outro foco (precificação e
// formalização), outro público. Não mistura respostas entre as duas.

import type { PesquisaConfig } from "./tipos";

export const pesquisaPrecificacao: PesquisaConfig = {
  slug: "pesquisa-precificacao",
  perguntas: [
    {
      id: "estagio",
      ordem: 1,
      parte: 1,
      tipo: "unica",
      titulo: "Onde você está com o seu negócio hoje?",
      opcoes: [
        { id: "ja_vendo", rotulo: "Já vendo faz um tempo" },
        { id: "comecei", rotulo: "Comecei a vender agora" },
        { id: "planejando", rotulo: "Ainda não vendo, tô planejando" },
      ],
    },
    {
      id: "tempo_negocio",
      ordem: 2,
      parte: 1,
      tipo: "unica",
      titulo: "Há quanto tempo o seu negócio existe?",
      opcoes: [
        { id: "menos_1_ano", rotulo: "Menos de 1 ano" },
        { id: "1_a_3_anos", rotulo: "1 a 3 anos" },
        { id: "3_a_5_anos", rotulo: "3 a 5 anos" },
        { id: "mais_5_anos", rotulo: "Mais de 5 anos" },
        { id: "nao_sei_dizer", rotulo: "Não sei dizer" },
      ],
    },
    {
      id: "formalizada",
      ordem: 3,
      parte: 1,
      tipo: "unica",
      titulo: "Você é formalizada?",
      opcoes: [
        { id: "informal", rotulo: "Ainda informal" },
        { id: "mei", rotulo: "MEI" },
        { id: "me", rotulo: "Microempresa (ME)" },
        { id: "nao_sei_dizer", rotulo: "Não sei dizer" },
      ],
    },
    {
      id: "categoria",
      ordem: 4,
      parte: 1,
      tipo: "unica",
      titulo: "O que você vende, ou pretende vender?",
      opcoes: [
        { id: "moda_acessorios", rotulo: "Roupa, bolsa e acessórios" },
        { id: "moda_intima_fitness", rotulo: "Moda íntima e fitness (lingerie, roupa de treino)" },
        { id: "beleza_estetica", rotulo: "Beleza e estética (salão, unha, cílios, sobrancelha)" },
        { id: "cosmeticos", rotulo: "Cosméticos e perfumaria (maquiagem, perfume, cremes)" },
        { id: "artesanato", rotulo: "Artesanato e coisas feitas à mão" },
        { id: "comida", rotulo: "Comida e doces (bolo, salgado, marmita)" },
        { id: "saude_bem_estar", rotulo: "Saúde e bem-estar (nutrição, terapia, personal)" },
        { id: "servicos", rotulo: "Serviços (consultoria, design, fotografia, redes sociais)" },
        { id: "educacao", rotulo: "Aulas, cursos ou mentoria" },
        { id: "digital", rotulo: "Produto digital (e-book, curso online, modelo pronto)" },
        { id: "casa_decoracao", rotulo: "Casa e decoração" },
        { id: "papelaria_presentes", rotulo: "Papelaria e presentes personalizados" },
        { id: "pet", rotulo: "Coisas pra pet (produtos ou serviços)" },
        { id: "infantil", rotulo: "Infantil (roupa, brinquedo, festa)" },
        { id: "revenda", rotulo: "Revenda ou catálogo de outras marcas" },
        { id: "outro", rotulo: "Outra coisa" },
      ],
    },
    {
      id: "quem_toca",
      ordem: 5,
      parte: 1,
      tipo: "unica",
      titulo: "Quem toca o negócio hoje?",
      opcoes: [
        { id: "so_eu", rotulo: "Só eu" },
        { id: "ajuda_informal", rotulo: "Eu e uma ajuda informal (família, parceria)" },
        { id: "contratadas_1_2", rotulo: "Eu e 1 ou 2 contratadas" },
        { id: "equipe_3", rotulo: "Uma equipe de 3 ou mais" },
      ],
    },
    {
      id: "faturamento",
      ordem: 6,
      parte: 1,
      tipo: "unica",
      opcional: true,
      titulo: "Quanto o negócio fatura por mês, mais ou menos?",
      opcoes: [
        { id: "ainda_nao", rotulo: "Ainda não faturo" },
        { id: "ate_1k", rotulo: "Até R$1 mil" },
        { id: "1_3k", rotulo: "De R$1 a 3 mil" },
        { id: "3_10k", rotulo: "De R$3 a 10 mil" },
        { id: "mais_10k", rotulo: "Mais de R$10 mil" },
        { id: "nao_dizer", rotulo: "Prefiro não dizer" },
      ],
    },
    {
      id: "onde_clareza",
      ordem: 7,
      parte: 1,
      tipo: "multipla",
      maxSelecoes: 2,
      titulo: "O que mais te faz sentir falta de clareza no negócio hoje?",
      opcoes: [
        { id: "quanto_cobrar", rotulo: "Não sei quanto cobrar" },
        { id: "dou_lucro", rotulo: "Não sei se dou lucro de verdade" },
        { id: "controle_caixa", rotulo: "Perco o controle do que entra e sai" },
        { id: "diferencial", rotulo: "Não sei o que me diferencia" },
        { id: "acham_caro", rotulo: "Minha cliente acha caro ou não entende meu valor" },
        { id: "quem_e_cliente", rotulo: "Não sei quem é a minha cliente" },
        { id: "no_controle", rotulo: "Me sinto no controle" },
      ],
    },
    {
      id: "aperto",
      ordem: 8,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo: "Com as suas palavras: qual é o maior aperto ou dúvida sobre o seu negócio hoje?",
    },
    {
      id: "inseguranca",
      ordem: 9,
      parte: 1,
      tipo: "unica",
      titulo: "O que te dá mais insegurança hoje?",
      opcoes: [
        { id: "marca", rotulo: "A minha marca e identidade" },
        { id: "precos", rotulo: "Os meus preços" },
        { id: "numeros", rotulo: "Os meus números" },
        { id: "nada", rotulo: "Nada, tô segura" },
      ],
    },
    {
      id: "separa_dinheiro",
      ordem: 10,
      parte: 1,
      tipo: "unica",
      titulo: "Você separa o dinheiro do negócio do seu dinheiro pessoal?",
      opcoes: [
        { id: "sempre", rotulo: "Sempre" },
        { id: "as_vezes", rotulo: "Às vezes" },
        { id: "tudo_junto", rotulo: "Não, é tudo junto" },
      ],
    },
    {
      id: "sabe_quanto_tira",
      ordem: 11,
      parte: 1,
      tipo: "unica",
      titulo: "Você sabe quanto consegue tirar pra você por mês, depois de pagar tudo do negócio?",
      opcoes: [
        { id: "sei_precisao", rotulo: "Sei com precisão" },
        { id: "sei_mais_ou_menos", rotulo: "Sei mais ou menos" },
        { id: "nao_faco_ideia", rotulo: "Não faço ideia" },
      ],
    },
    {
      id: "ferramentas_pagas",
      ordem: 12,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo:
        "Hoje você já paga por alguma ferramenta ou serviço pro negócio (app, sistema, contador, curso)? Quais e quanto mais ou menos por mês?",
    },
    {
      id: "preco_comecaria_cara",
      ordem: 13,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo: "A partir de quanto por mês ela começaria a ficar cara, mas você ainda pensaria em assinar?",
    },
    {
      id: "preco_cara_demais",
      ordem: 14,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo: "A partir de quanto seria cara demais e você nem consideraria?",
    },
    {
      id: "preco_bom_negocio",
      ordem: 15,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo: "Por quanto por mês seria um bom negócio, valeria super a pena?",
    },
    {
      id: "preco_barata_demais",
      ordem: 16,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo: "E por quanto seria barata demais, a ponto de você desconfiar que não entrega direito?",
    },
    {
      id: "episodio",
      ordem: 17,
      parte: 1,
      tipo: "aberta",
      opcional: true,
      titulo:
        "Me conta a última vez que você se sentiu perdida ou insegura numa decisão do negócio. O que aconteceu?",
    },
  ],
};
