/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as ListaDeEsperaRouteImport } from './routes/lista-de-espera'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as CompraConfirmadaRouteImport } from './routes/compra-confirmada'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthVerificacaoRouteImport } from './routes/auth/verificacao'
import { Route as AuthRedefinirSenhaRouteImport } from './routes/auth/redefinir-senha'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLinkExpiradoRouteImport } from './routes/auth/link-expirado'
import { Route as AuthEsqueciSenhaRouteImport } from './routes/auth/esqueci-senha'
import { Route as AuthCadastroRouteImport } from './routes/auth/cadastro'
import { Route as AuthenticatedVendasEClientesRouteImport } from './routes/_authenticated/vendas-e-clientes'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMercadoRouteImport } from './routes/_authenticated/mercado'
import { Route as AuthenticatedMarcaVivaRouteImport } from './routes/_authenticated/marca-viva'
import { Route as AuthenticatedMarcaRouteImport } from './routes/_authenticated/marca'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEntregaveisRouteImport } from './routes/_authenticated/entregaveis'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCalendarioRouteImport } from './routes/_authenticated/calendario'
import { Route as AuthenticatedCadernoRouteImport } from './routes/_authenticated/caderno'
import { Route as AuthenticatedAssinarRouteImport } from './routes/_authenticated/assinar'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedPlanejamentoIndexRouteImport } from './routes/_authenticated/planejamento.index'
import { Route as AuthenticatedBlogAdminIndexRouteImport } from './routes/_authenticated/blog-admin.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedPlannerSlugRouteImport } from './routes/_authenticated/planner.$slug'
import { Route as AuthenticatedPlanejamentoCompletoRouteImport } from './routes/_authenticated/planejamento.completo'
import { Route as AuthenticatedEtapaNRouteImport } from './routes/_authenticated/etapa.$n'
import { Route as AuthenticatedBlogAdminNovoRouteImport } from './routes/_authenticated/blog-admin.novo'
import { Route as AuthenticatedBlogAdminIdRouteImport } from './routes/_authenticated/blog-admin.$id'
import { Route as AuthenticatedAdminQualidadeRouteImport } from './routes/_authenticated/admin.qualidade'
import { Route as AuthenticatedAdminPesquisasRouteImport } from './routes/_authenticated/admin.pesquisas'
import { Route as AuthenticatedAdminNegocioRouteImport } from './routes/_authenticated/admin.negocio'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminGovernancaRouteImport } from './routes/_authenticated/admin.governanca'
import { Route as AuthenticatedAdminFunilRouteImport } from './routes/_authenticated/admin.funil'
import { Route as AuthenticatedAdminFlagsRouteImport } from './routes/_authenticated/admin.flags'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin.auditoria'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAlertasRouteImport } from './routes/_authenticated/admin.alertas'
import { Route as AuthenticatedAdminChamadosIndexRouteImport } from './routes/_authenticated/admin.chamados.index'
import { Route as AuthenticatedPlanejamentoModuloNRouteImport } from './routes/_authenticated/planejamento.modulo.$n'
import { Route as AuthenticatedAdminUsuariosIdRouteImport } from './routes/_authenticated/admin.usuarios.$id'
import { Route as AuthenticatedAdminChamadosIdRouteImport } from './routes/_authenticated/admin.chamados.$id'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaDeEsperaRoute = ListaDeEsperaRouteImport.update({
  id: '/lista-de-espera',
  path: '/lista-de-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const CompraConfirmadaRoute = CompraConfirmadaRouteImport.update({
  id: '/compra-confirmada',
  path: '/compra-confirmada',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificacaoRoute = AuthVerificacaoRouteImport.update({
  id: '/auth/verificacao',
  path: '/auth/verificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedefinirSenhaRoute = AuthRedefinirSenhaRouteImport.update({
  id: '/auth/redefinir-senha',
  path: '/auth/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLinkExpiradoRoute = AuthLinkExpiradoRouteImport.update({
  id: '/auth/link-expirado',
  path: '/auth/link-expirado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEsqueciSenhaRoute = AuthEsqueciSenhaRouteImport.update({
  id: '/auth/esqueci-senha',
  path: '/auth/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasEClientesRoute =
  AuthenticatedVendasEClientesRouteImport.update({
    id: '/vendas-e-clientes',
    path: '/vendas-e-clientes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMercadoRoute = AuthenticatedMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarcaVivaRoute = AuthenticatedMarcaVivaRouteImport.update({
  id: '/marca-viva',
  path: '/marca-viva',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarcaRoute = AuthenticatedMarcaRouteImport.update({
  id: '/marca',
  path: '/marca',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntregaveisRoute =
  AuthenticatedEntregaveisRouteImport.update({
    id: '/entregaveis',
    path: '/entregaveis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarioRoute = AuthenticatedCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCadernoRoute = AuthenticatedCadernoRouteImport.update({
  id: '/caderno',
  path: '/caderno',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssinarRoute = AuthenticatedAssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanejamentoIndexRoute =
  AuthenticatedPlanejamentoIndexRouteImport.update({
    id: '/planejamento/',
    path: '/planejamento/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogAdminIndexRoute =
  AuthenticatedBlogAdminIndexRouteImport.update({
    id: '/blog-admin/',
    path: '/blog-admin/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedPlannerSlugRoute =
  AuthenticatedPlannerSlugRouteImport.update({
    id: '/planner/$slug',
    path: '/planner/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlanejamentoCompletoRoute =
  AuthenticatedPlanejamentoCompletoRouteImport.update({
    id: '/planejamento/completo',
    path: '/planejamento/completo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEtapaNRoute = AuthenticatedEtapaNRouteImport.update({
  id: '/etapa/$n',
  path: '/etapa/$n',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogAdminNovoRoute =
  AuthenticatedBlogAdminNovoRouteImport.update({
    id: '/blog-admin/novo',
    path: '/blog-admin/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBlogAdminIdRoute =
  AuthenticatedBlogAdminIdRouteImport.update({
    id: '/blog-admin/$id',
    path: '/blog-admin/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQualidadeRoute =
  AuthenticatedAdminQualidadeRouteImport.update({
    id: '/qualidade',
    path: '/qualidade',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPesquisasRoute =
  AuthenticatedAdminPesquisasRouteImport.update({
    id: '/pesquisas',
    path: '/pesquisas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNegocioRoute =
  AuthenticatedAdminNegocioRouteImport.update({
    id: '/negocio',
    path: '/negocio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminGovernancaRoute =
  AuthenticatedAdminGovernancaRouteImport.update({
    id: '/governanca',
    path: '/governanca',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFunilRoute = AuthenticatedAdminFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFlagsRoute = AuthenticatedAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlertasRoute =
  AuthenticatedAdminAlertasRouteImport.update({
    id: '/alertas',
    path: '/alertas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChamadosIndexRoute =
  AuthenticatedAdminChamadosIndexRouteImport.update({
    id: '/chamados/',
    path: '/chamados/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPlanejamentoModuloNRoute =
  AuthenticatedPlanejamentoModuloNRouteImport.update({
    id: '/planejamento/modulo/$n',
    path: '/planejamento/modulo/$n',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosIdRoute =
  AuthenticatedAdminUsuariosIdRouteImport.update({
    id: '/usuarios/$id',
    path: '/usuarios/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChamadosIdRoute =
  AuthenticatedAdminChamadosIdRouteImport.update({
    id: '/chamados/$id',
    path: '/chamados/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/compra-confirmada': typeof CompraConfirmadaRoute
  '/design-system': typeof DesignSystemRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/assinar': typeof AuthenticatedAssinarRoute
  '/caderno': typeof AuthenticatedCadernoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/entregaveis': typeof AuthenticatedEntregaveisRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/marca-viva': typeof AuthenticatedMarcaVivaRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas-e-clientes': typeof AuthenticatedVendasEClientesRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/link-expirado': typeof AuthLinkExpiradoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/funil': typeof AuthenticatedAdminFunilRoute
  '/admin/governanca': typeof AuthenticatedAdminGovernancaRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/negocio': typeof AuthenticatedAdminNegocioRoute
  '/admin/pesquisas': typeof AuthenticatedAdminPesquisasRoute
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/blog-admin/$id': typeof AuthenticatedBlogAdminIdRoute
  '/blog-admin/novo': typeof AuthenticatedBlogAdminNovoRoute
  '/etapa/$n': typeof AuthenticatedEtapaNRoute
  '/planejamento/completo': typeof AuthenticatedPlanejamentoCompletoRoute
  '/planner/$slug': typeof AuthenticatedPlannerSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/blog-admin/': typeof AuthenticatedBlogAdminIndexRoute
  '/planejamento/': typeof AuthenticatedPlanejamentoIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/admin/chamados/$id': typeof AuthenticatedAdminChamadosIdRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/planejamento/modulo/$n': typeof AuthenticatedPlanejamentoModuloNRoute
  '/admin/chamados/': typeof AuthenticatedAdminChamadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/compra-confirmada': typeof CompraConfirmadaRoute
  '/design-system': typeof DesignSystemRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/assinar': typeof AuthenticatedAssinarRoute
  '/caderno': typeof AuthenticatedCadernoRoute
  '/calendario': typeof AuthenticatedCalendarioRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/entregaveis': typeof AuthenticatedEntregaveisRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/jornada': typeof AuthenticatedJornadaRoute
  '/marca': typeof AuthenticatedMarcaRoute
  '/marca-viva': typeof AuthenticatedMarcaVivaRoute
  '/mercado': typeof AuthenticatedMercadoRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/vendas-e-clientes': typeof AuthenticatedVendasEClientesRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/link-expirado': typeof AuthLinkExpiradoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/admin/funil': typeof AuthenticatedAdminFunilRoute
  '/admin/governanca': typeof AuthenticatedAdminGovernancaRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/negocio': typeof AuthenticatedAdminNegocioRoute
  '/admin/pesquisas': typeof AuthenticatedAdminPesquisasRoute
  '/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/blog-admin/$id': typeof AuthenticatedBlogAdminIdRoute
  '/blog-admin/novo': typeof AuthenticatedBlogAdminNovoRoute
  '/etapa/$n': typeof AuthenticatedEtapaNRoute
  '/planejamento/completo': typeof AuthenticatedPlanejamentoCompletoRoute
  '/planner/$slug': typeof AuthenticatedPlannerSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/blog-admin': typeof AuthenticatedBlogAdminIndexRoute
  '/planejamento': typeof AuthenticatedPlanejamentoIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/admin/chamados/$id': typeof AuthenticatedAdminChamadosIdRoute
  '/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/planejamento/modulo/$n': typeof AuthenticatedPlanejamentoModuloNRoute
  '/admin/chamados': typeof AuthenticatedAdminChamadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ajuda': typeof AjudaRoute
  '/compra-confirmada': typeof CompraConfirmadaRoute
  '/design-system': typeof DesignSystemRoute
  '/lista-de-espera': typeof ListaDeEsperaRoute
  '/pesquisa': typeof PesquisaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/assinar': typeof AuthenticatedAssinarRoute
  '/_authenticated/caderno': typeof AuthenticatedCadernoRoute
  '/_authenticated/calendario': typeof AuthenticatedCalendarioRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/entregaveis': typeof AuthenticatedEntregaveisRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRoute
  '/_authenticated/marca': typeof AuthenticatedMarcaRoute
  '/_authenticated/marca-viva': typeof AuthenticatedMarcaVivaRoute
  '/_authenticated/mercado': typeof AuthenticatedMercadoRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/vendas-e-clientes': typeof AuthenticatedVendasEClientesRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci-senha': typeof AuthEsqueciSenhaRoute
  '/auth/link-expirado': typeof AuthLinkExpiradoRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir-senha': typeof AuthRedefinirSenhaRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/alertas': typeof AuthenticatedAdminAlertasRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/flags': typeof AuthenticatedAdminFlagsRoute
  '/_authenticated/admin/funil': typeof AuthenticatedAdminFunilRoute
  '/_authenticated/admin/governanca': typeof AuthenticatedAdminGovernancaRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/negocio': typeof AuthenticatedAdminNegocioRoute
  '/_authenticated/admin/pesquisas': typeof AuthenticatedAdminPesquisasRoute
  '/_authenticated/admin/qualidade': typeof AuthenticatedAdminQualidadeRoute
  '/_authenticated/blog-admin/$id': typeof AuthenticatedBlogAdminIdRoute
  '/_authenticated/blog-admin/novo': typeof AuthenticatedBlogAdminNovoRoute
  '/_authenticated/etapa/$n': typeof AuthenticatedEtapaNRoute
  '/_authenticated/planejamento/completo': typeof AuthenticatedPlanejamentoCompletoRoute
  '/_authenticated/planner/$slug': typeof AuthenticatedPlannerSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/blog-admin/': typeof AuthenticatedBlogAdminIndexRoute
  '/_authenticated/planejamento/': typeof AuthenticatedPlanejamentoIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/admin/chamados/$id': typeof AuthenticatedAdminChamadosIdRoute
  '/_authenticated/admin/usuarios/$id': typeof AuthenticatedAdminUsuariosIdRoute
  '/_authenticated/planejamento/modulo/$n': typeof AuthenticatedPlanejamentoModuloNRoute
  '/_authenticated/admin/chamados/': typeof AuthenticatedAdminChamadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/compra-confirmada'
    | '/design-system'
    | '/lista-de-espera'
    | '/pesquisa'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/admin'
    | '/assinar'
    | '/caderno'
    | '/calendario'
    | '/clientes'
    | '/configuracoes'
    | '/entregaveis'
    | '/equipe'
    | '/financeiro'
    | '/jornada'
    | '/marca'
    | '/marca-viva'
    | '/mercado'
    | '/metas'
    | '/onboarding'
    | '/painel'
    | '/produtos'
    | '/vendas-e-clientes'
    | '/auth/cadastro'
    | '/auth/esqueci-senha'
    | '/auth/link-expirado'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/auth/verificacao'
    | '/blog/$slug'
    | '/blog/'
    | '/admin/alertas'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/crm'
    | '/admin/flags'
    | '/admin/funil'
    | '/admin/governanca'
    | '/admin/logs'
    | '/admin/negocio'
    | '/admin/pesquisas'
    | '/admin/qualidade'
    | '/blog-admin/$id'
    | '/blog-admin/novo'
    | '/etapa/$n'
    | '/planejamento/completo'
    | '/planner/$slug'
    | '/admin/'
    | '/blog-admin/'
    | '/planejamento/'
    | '/planner/'
    | '/admin/chamados/$id'
    | '/admin/usuarios/$id'
    | '/planejamento/modulo/$n'
    | '/admin/chamados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/compra-confirmada'
    | '/design-system'
    | '/lista-de-espera'
    | '/pesquisa'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/assinar'
    | '/caderno'
    | '/calendario'
    | '/clientes'
    | '/configuracoes'
    | '/entregaveis'
    | '/equipe'
    | '/financeiro'
    | '/jornada'
    | '/marca'
    | '/marca-viva'
    | '/mercado'
    | '/metas'
    | '/onboarding'
    | '/painel'
    | '/produtos'
    | '/vendas-e-clientes'
    | '/auth/cadastro'
    | '/auth/esqueci-senha'
    | '/auth/link-expirado'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/auth/verificacao'
    | '/blog/$slug'
    | '/blog'
    | '/admin/alertas'
    | '/admin/analytics'
    | '/admin/auditoria'
    | '/admin/crm'
    | '/admin/flags'
    | '/admin/funil'
    | '/admin/governanca'
    | '/admin/logs'
    | '/admin/negocio'
    | '/admin/pesquisas'
    | '/admin/qualidade'
    | '/blog-admin/$id'
    | '/blog-admin/novo'
    | '/etapa/$n'
    | '/planejamento/completo'
    | '/planner/$slug'
    | '/admin'
    | '/blog-admin'
    | '/planejamento'
    | '/planner'
    | '/admin/chamados/$id'
    | '/admin/usuarios/$id'
    | '/planejamento/modulo/$n'
    | '/admin/chamados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ajuda'
    | '/compra-confirmada'
    | '/design-system'
    | '/lista-de-espera'
    | '/pesquisa'
    | '/privacidade'
    | '/sobre'
    | '/termos'
    | '/_authenticated/admin'
    | '/_authenticated/assinar'
    | '/_authenticated/caderno'
    | '/_authenticated/calendario'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/entregaveis'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/jornada'
    | '/_authenticated/marca'
    | '/_authenticated/marca-viva'
    | '/_authenticated/mercado'
    | '/_authenticated/metas'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/_authenticated/produtos'
    | '/_authenticated/vendas-e-clientes'
    | '/auth/cadastro'
    | '/auth/esqueci-senha'
    | '/auth/link-expirado'
    | '/auth/login'
    | '/auth/redefinir-senha'
    | '/auth/verificacao'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/admin/alertas'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/flags'
    | '/_authenticated/admin/funil'
    | '/_authenticated/admin/governanca'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/negocio'
    | '/_authenticated/admin/pesquisas'
    | '/_authenticated/admin/qualidade'
    | '/_authenticated/blog-admin/$id'
    | '/_authenticated/blog-admin/novo'
    | '/_authenticated/etapa/$n'
    | '/_authenticated/planejamento/completo'
    | '/_authenticated/planner/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/blog-admin/'
    | '/_authenticated/planejamento/'
    | '/_authenticated/planner/'
    | '/_authenticated/admin/chamados/$id'
    | '/_authenticated/admin/usuarios/$id'
    | '/_authenticated/planejamento/modulo/$n'
    | '/_authenticated/admin/chamados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AjudaRoute: typeof AjudaRoute
  CompraConfirmadaRoute: typeof CompraConfirmadaRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ListaDeEsperaRoute: typeof ListaDeEsperaRoute
  PesquisaRoute: typeof PesquisaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthEsqueciSenhaRoute: typeof AuthEsqueciSenhaRoute
  AuthLinkExpiradoRoute: typeof AuthLinkExpiradoRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRedefinirSenhaRoute: typeof AuthRedefinirSenhaRoute
  AuthVerificacaoRoute: typeof AuthVerificacaoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-de-espera': {
      id: '/lista-de-espera'
      path: '/lista-de-espera'
      fullPath: '/lista-de-espera'
      preLoaderRoute: typeof ListaDeEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compra-confirmada': {
      id: '/compra-confirmada'
      path: '/compra-confirmada'
      fullPath: '/compra-confirmada'
      preLoaderRoute: typeof CompraConfirmadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verificacao': {
      id: '/auth/verificacao'
      path: '/auth/verificacao'
      fullPath: '/auth/verificacao'
      preLoaderRoute: typeof AuthVerificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redefinir-senha': {
      id: '/auth/redefinir-senha'
      path: '/auth/redefinir-senha'
      fullPath: '/auth/redefinir-senha'
      preLoaderRoute: typeof AuthRedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/link-expirado': {
      id: '/auth/link-expirado'
      path: '/auth/link-expirado'
      fullPath: '/auth/link-expirado'
      preLoaderRoute: typeof AuthLinkExpiradoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/esqueci-senha': {
      id: '/auth/esqueci-senha'
      path: '/auth/esqueci-senha'
      fullPath: '/auth/esqueci-senha'
      preLoaderRoute: typeof AuthEsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas-e-clientes': {
      id: '/_authenticated/vendas-e-clientes'
      path: '/vendas-e-clientes'
      fullPath: '/vendas-e-clientes'
      preLoaderRoute: typeof AuthenticatedVendasEClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mercado': {
      id: '/_authenticated/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof AuthenticatedMercadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marca-viva': {
      id: '/_authenticated/marca-viva'
      path: '/marca-viva'
      fullPath: '/marca-viva'
      preLoaderRoute: typeof AuthenticatedMarcaVivaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marca': {
      id: '/_authenticated/marca'
      path: '/marca'
      fullPath: '/marca'
      preLoaderRoute: typeof AuthenticatedMarcaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entregaveis': {
      id: '/_authenticated/entregaveis'
      path: '/entregaveis'
      fullPath: '/entregaveis'
      preLoaderRoute: typeof AuthenticatedEntregaveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendario': {
      id: '/_authenticated/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedCalendarioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/caderno': {
      id: '/_authenticated/caderno'
      path: '/caderno'
      fullPath: '/caderno'
      preLoaderRoute: typeof AuthenticatedCadernoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assinar': {
      id: '/_authenticated/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AuthenticatedAssinarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planejamento/': {
      id: '/_authenticated/planejamento/'
      path: '/planejamento'
      fullPath: '/planejamento/'
      preLoaderRoute: typeof AuthenticatedPlanejamentoIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog-admin/': {
      id: '/_authenticated/blog-admin/'
      path: '/blog-admin'
      fullPath: '/blog-admin/'
      preLoaderRoute: typeof AuthenticatedBlogAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/planner/$slug': {
      id: '/_authenticated/planner/$slug'
      path: '/planner/$slug'
      fullPath: '/planner/$slug'
      preLoaderRoute: typeof AuthenticatedPlannerSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planejamento/completo': {
      id: '/_authenticated/planejamento/completo'
      path: '/planejamento/completo'
      fullPath: '/planejamento/completo'
      preLoaderRoute: typeof AuthenticatedPlanejamentoCompletoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/$n': {
      id: '/_authenticated/etapa/$n'
      path: '/etapa/$n'
      fullPath: '/etapa/$n'
      preLoaderRoute: typeof AuthenticatedEtapaNRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog-admin/novo': {
      id: '/_authenticated/blog-admin/novo'
      path: '/blog-admin/novo'
      fullPath: '/blog-admin/novo'
      preLoaderRoute: typeof AuthenticatedBlogAdminNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blog-admin/$id': {
      id: '/_authenticated/blog-admin/$id'
      path: '/blog-admin/$id'
      fullPath: '/blog-admin/$id'
      preLoaderRoute: typeof AuthenticatedBlogAdminIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/qualidade': {
      id: '/_authenticated/admin/qualidade'
      path: '/qualidade'
      fullPath: '/admin/qualidade'
      preLoaderRoute: typeof AuthenticatedAdminQualidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pesquisas': {
      id: '/_authenticated/admin/pesquisas'
      path: '/pesquisas'
      fullPath: '/admin/pesquisas'
      preLoaderRoute: typeof AuthenticatedAdminPesquisasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/negocio': {
      id: '/_authenticated/admin/negocio'
      path: '/negocio'
      fullPath: '/admin/negocio'
      preLoaderRoute: typeof AuthenticatedAdminNegocioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/governanca': {
      id: '/_authenticated/admin/governanca'
      path: '/governanca'
      fullPath: '/admin/governanca'
      preLoaderRoute: typeof AuthenticatedAdminGovernancaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/funil': {
      id: '/_authenticated/admin/funil'
      path: '/funil'
      fullPath: '/admin/funil'
      preLoaderRoute: typeof AuthenticatedAdminFunilRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/flags': {
      id: '/_authenticated/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AuthenticatedAdminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alertas': {
      id: '/_authenticated/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AuthenticatedAdminAlertasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chamados/': {
      id: '/_authenticated/admin/chamados/'
      path: '/chamados'
      fullPath: '/admin/chamados/'
      preLoaderRoute: typeof AuthenticatedAdminChamadosIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/planejamento/modulo/$n': {
      id: '/_authenticated/planejamento/modulo/$n'
      path: '/planejamento/modulo/$n'
      fullPath: '/planejamento/modulo/$n'
      preLoaderRoute: typeof AuthenticatedPlanejamentoModuloNRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios/$id': {
      id: '/_authenticated/admin/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chamados/$id': {
      id: '/_authenticated/admin/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/admin/chamados/$id'
      preLoaderRoute: typeof AuthenticatedAdminChamadosIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAlertasRoute: typeof AuthenticatedAdminAlertasRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminFlagsRoute: typeof AuthenticatedAdminFlagsRoute
  AuthenticatedAdminFunilRoute: typeof AuthenticatedAdminFunilRoute
  AuthenticatedAdminGovernancaRoute: typeof AuthenticatedAdminGovernancaRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminNegocioRoute: typeof AuthenticatedAdminNegocioRoute
  AuthenticatedAdminPesquisasRoute: typeof AuthenticatedAdminPesquisasRoute
  AuthenticatedAdminQualidadeRoute: typeof AuthenticatedAdminQualidadeRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminChamadosIdRoute: typeof AuthenticatedAdminChamadosIdRoute
  AuthenticatedAdminUsuariosIdRoute: typeof AuthenticatedAdminUsuariosIdRoute
  AuthenticatedAdminChamadosIndexRoute: typeof AuthenticatedAdminChamadosIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAlertasRoute: AuthenticatedAdminAlertasRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminFlagsRoute: AuthenticatedAdminFlagsRoute,
  AuthenticatedAdminFunilRoute: AuthenticatedAdminFunilRoute,
  AuthenticatedAdminGovernancaRoute: AuthenticatedAdminGovernancaRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminNegocioRoute: AuthenticatedAdminNegocioRoute,
  AuthenticatedAdminPesquisasRoute: AuthenticatedAdminPesquisasRoute,
  AuthenticatedAdminQualidadeRoute: AuthenticatedAdminQualidadeRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminChamadosIdRoute: AuthenticatedAdminChamadosIdRoute,
  AuthenticatedAdminUsuariosIdRoute: AuthenticatedAdminUsuariosIdRoute,
  AuthenticatedAdminChamadosIndexRoute: AuthenticatedAdminChamadosIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAssinarRoute: typeof AuthenticatedAssinarRoute
  AuthenticatedCadernoRoute: typeof AuthenticatedCadernoRoute
  AuthenticatedCalendarioRoute: typeof AuthenticatedCalendarioRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedEntregaveisRoute: typeof AuthenticatedEntregaveisRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRoute
  AuthenticatedMarcaRoute: typeof AuthenticatedMarcaRoute
  AuthenticatedMarcaVivaRoute: typeof AuthenticatedMarcaVivaRoute
  AuthenticatedMercadoRoute: typeof AuthenticatedMercadoRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedVendasEClientesRoute: typeof AuthenticatedVendasEClientesRoute
  AuthenticatedBlogAdminIdRoute: typeof AuthenticatedBlogAdminIdRoute
  AuthenticatedBlogAdminNovoRoute: typeof AuthenticatedBlogAdminNovoRoute
  AuthenticatedEtapaNRoute: typeof AuthenticatedEtapaNRoute
  AuthenticatedPlanejamentoCompletoRoute: typeof AuthenticatedPlanejamentoCompletoRoute
  AuthenticatedPlannerSlugRoute: typeof AuthenticatedPlannerSlugRoute
  AuthenticatedBlogAdminIndexRoute: typeof AuthenticatedBlogAdminIndexRoute
  AuthenticatedPlanejamentoIndexRoute: typeof AuthenticatedPlanejamentoIndexRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
  AuthenticatedPlanejamentoModuloNRoute: typeof AuthenticatedPlanejamentoModuloNRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAssinarRoute: AuthenticatedAssinarRoute,
  AuthenticatedCadernoRoute: AuthenticatedCadernoRoute,
  AuthenticatedCalendarioRoute: AuthenticatedCalendarioRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedEntregaveisRoute: AuthenticatedEntregaveisRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRoute,
  AuthenticatedMarcaRoute: AuthenticatedMarcaRoute,
  AuthenticatedMarcaVivaRoute: AuthenticatedMarcaVivaRoute,
  AuthenticatedMercadoRoute: AuthenticatedMercadoRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedVendasEClientesRoute: AuthenticatedVendasEClientesRoute,
  AuthenticatedBlogAdminIdRoute: AuthenticatedBlogAdminIdRoute,
  AuthenticatedBlogAdminNovoRoute: AuthenticatedBlogAdminNovoRoute,
  AuthenticatedEtapaNRoute: AuthenticatedEtapaNRoute,
  AuthenticatedPlanejamentoCompletoRoute:
    AuthenticatedPlanejamentoCompletoRoute,
  AuthenticatedPlannerSlugRoute: AuthenticatedPlannerSlugRoute,
  AuthenticatedBlogAdminIndexRoute: AuthenticatedBlogAdminIndexRoute,
  AuthenticatedPlanejamentoIndexRoute: AuthenticatedPlanejamentoIndexRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
  AuthenticatedPlanejamentoModuloNRoute: AuthenticatedPlanejamentoModuloNRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AjudaRoute: AjudaRoute,
  CompraConfirmadaRoute: CompraConfirmadaRoute,
  DesignSystemRoute: DesignSystemRoute,
  ListaDeEsperaRoute: ListaDeEsperaRoute,
  PesquisaRoute: PesquisaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthEsqueciSenhaRoute: AuthEsqueciSenhaRoute,
  AuthLinkExpiradoRoute: AuthLinkExpiradoRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRedefinirSenhaRoute: AuthRedefinirSenhaRoute,
  AuthVerificacaoRoute: AuthVerificacaoRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
