/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerificacaoRouteImport } from './routes/auth/verificacao'
import { Route as AuthRedefinirRouteImport } from './routes/auth/redefinir'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthEsqueciRouteImport } from './routes/auth/esqueci'
import { Route as AuthCadastroRouteImport } from './routes/auth/cadastro'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedEtapa8RouteImport } from './routes/_authenticated/etapa.8'
import { Route as AuthenticatedEtapa8RouteImport } from './routes/_authenticated/etapa.8'
import { Route as AuthenticatedEtapa7RouteImport } from './routes/_authenticated/etapa.7'
import { Route as AuthenticatedEtapa6RouteImport } from './routes/_authenticated/etapa.6'
import { Route as AuthenticatedEtapa5RouteImport } from './routes/_authenticated/etapa.5'
import { Route as AuthenticatedEtapa4RouteImport } from './routes/_authenticated/etapa.4'
import { Route as AuthenticatedEtapa3RouteImport } from './routes/_authenticated/etapa.3'
import { Route as AuthenticatedEtapa2RouteImport } from './routes/_authenticated/etapa.2'
import { Route as AuthenticatedEtapa1RouteImport } from './routes/_authenticated/etapa.1'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificacaoRoute = AuthVerificacaoRouteImport.update({
  id: '/auth/verificacao',
  path: '/auth/verificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRedefinirRoute = AuthRedefinirRouteImport.update({
  id: '/auth/redefinir',
  path: '/auth/redefinir',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEsqueciRoute = AuthEsqueciRouteImport.update({
  id: '/auth/esqueci',
  path: '/auth/esqueci',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroRoute = AuthCadastroRouteImport.update({
  id: '/auth/cadastro',
  path: '/auth/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa8Route = AuthenticatedEtapa8RouteImport.update({
  id: '/etapa/8',
  path: '/etapa/8',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa7Route = AuthenticatedEtapa7RouteImport.update({
  id: '/etapa/7',
  path: '/etapa/7',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa6Route = AuthenticatedEtapa6RouteImport.update({
  id: '/etapa/6',
  path: '/etapa/6',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa5Route = AuthenticatedEtapa5RouteImport.update({
  id: '/etapa/5',
  path: '/etapa/5',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa4Route = AuthenticatedEtapa4RouteImport.update({
  id: '/etapa/4',
  path: '/etapa/4',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa3Route = AuthenticatedEtapa3RouteImport.update({
  id: '/etapa/3',
  path: '/etapa/3',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa2Route = AuthenticatedEtapa2RouteImport.update({
  id: '/etapa/2',
  path: '/etapa/2',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtapa1Route = AuthenticatedEtapa1RouteImport.update({
  id: '/etapa/1',
  path: '/etapa/1',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci': typeof AuthEsqueciRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/etapa/1': typeof AuthenticatedEtapa1Route
  '/etapa/2': typeof AuthenticatedEtapa2Route
  '/etapa/3': typeof AuthenticatedEtapa3Route
  '/etapa/4': typeof AuthenticatedEtapa4Route
  '/etapa/5': typeof AuthenticatedEtapa5Route
  '/etapa/6': typeof AuthenticatedEtapa6Route
  '/etapa/7': typeof AuthenticatedEtapa7Route
  '/etapa/8': typeof AuthenticatedEtapa8Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci': typeof AuthEsqueciRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/etapa/1': typeof AuthenticatedEtapa1Route
  '/etapa/2': typeof AuthenticatedEtapa2Route
  '/etapa/3': typeof AuthenticatedEtapa3Route
  '/etapa/4': typeof AuthenticatedEtapa4Route
  '/etapa/5': typeof AuthenticatedEtapa5Route
  '/etapa/6': typeof AuthenticatedEtapa6Route
  '/etapa/7': typeof AuthenticatedEtapa7Route
  '/etapa/8': typeof AuthenticatedEtapa8Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/auth/cadastro': typeof AuthCadastroRoute
  '/auth/esqueci': typeof AuthEsqueciRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/redefinir': typeof AuthRedefinirRoute
  '/auth/verificacao': typeof AuthVerificacaoRoute
  '/_authenticated/etapa/1': typeof AuthenticatedEtapa1Route
  '/_authenticated/etapa/2': typeof AuthenticatedEtapa2Route
  '/_authenticated/etapa/3': typeof AuthenticatedEtapa3Route
  '/_authenticated/etapa/4': typeof AuthenticatedEtapa4Route
  '/_authenticated/etapa/5': typeof AuthenticatedEtapa5Route
  '/_authenticated/etapa/6': typeof AuthenticatedEtapa6Route
  '/_authenticated/etapa/7': typeof AuthenticatedEtapa7Route
  '/_authenticated/etapa/8': typeof AuthenticatedEtapa8Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/painel'
    | '/auth/cadastro'
    | '/auth/esqueci'
    | '/auth/login'
    | '/auth/redefinir'
    | '/auth/verificacao'
    | '/etapa/1'
    | '/etapa/2'
    | '/etapa/3'
    | '/etapa/4'
    | '/etapa/5'
    | '/etapa/6'
    | '/etapa/7'
    | '/etapa/8'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/painel'
    | '/auth/cadastro'
    | '/auth/esqueci'
    | '/auth/login'
    | '/auth/redefinir'
    | '/auth/verificacao'
    | '/etapa/1'
    | '/etapa/2'
    | '/etapa/3'
    | '/etapa/4'
    | '/etapa/5'
    | '/etapa/6'
    | '/etapa/7'
    | '/etapa/8'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/onboarding'
    | '/_authenticated/painel'
    | '/auth/cadastro'
    | '/auth/esqueci'
    | '/auth/login'
    | '/auth/redefinir'
    | '/auth/verificacao'
    | '/_authenticated/etapa/1'
    | '/_authenticated/etapa/2'
    | '/_authenticated/etapa/3'
    | '/_authenticated/etapa/4'
    | '/_authenticated/etapa/5'
    | '/_authenticated/etapa/6'
    | '/_authenticated/etapa/7'
    | '/_authenticated/etapa/8'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthCadastroRoute: typeof AuthCadastroRoute
  AuthEsqueciRoute: typeof AuthEsqueciRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRedefinirRoute: typeof AuthRedefinirRoute
  AuthVerificacaoRoute: typeof AuthVerificacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verificacao': {
      id: '/auth/verificacao'
      path: '/auth/verificacao'
      fullPath: '/auth/verificacao'
      preLoaderRoute: typeof AuthVerificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/redefinir': {
      id: '/auth/redefinir'
      path: '/auth/redefinir'
      fullPath: '/auth/redefinir'
      preLoaderRoute: typeof AuthRedefinirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/esqueci': {
      id: '/auth/esqueci'
      path: '/auth/esqueci'
      fullPath: '/auth/esqueci'
      preLoaderRoute: typeof AuthEsqueciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/cadastro': {
      id: '/auth/cadastro'
      path: '/auth/cadastro'
      fullPath: '/auth/cadastro'
      preLoaderRoute: typeof AuthCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/8': {
      id: '/_authenticated/etapa/8'
      path: '/etapa/8'
      fullPath: '/etapa/8'
      preLoaderRoute: typeof AuthenticatedEtapa8RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/7': {
      id: '/_authenticated/etapa/7'
      path: '/etapa/7'
      fullPath: '/etapa/7'
      preLoaderRoute: typeof AuthenticatedEtapa7RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/6': {
      id: '/_authenticated/etapa/6'
      path: '/etapa/6'
      fullPath: '/etapa/6'
      preLoaderRoute: typeof AuthenticatedEtapa6RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/5': {
      id: '/_authenticated/etapa/5'
      path: '/etapa/5'
      fullPath: '/etapa/5'
      preLoaderRoute: typeof AuthenticatedEtapa5RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/4': {
      id: '/_authenticated/etapa/4'
      path: '/etapa/4'
      fullPath: '/etapa/4'
      preLoaderRoute: typeof AuthenticatedEtapa4RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/3': {
      id: '/_authenticated/etapa/3'
      path: '/etapa/3'
      fullPath: '/etapa/3'
      preLoaderRoute: typeof AuthenticatedEtapa3RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/2': {
      id: '/_authenticated/etapa/2'
      path: '/etapa/2'
      fullPath: '/etapa/2'
      preLoaderRoute: typeof AuthenticatedEtapa2RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etapa/1': {
      id: '/_authenticated/etapa/1'
      path: '/etapa/1'
      fullPath: '/etapa/1'
      preLoaderRoute: typeof AuthenticatedEtapa1RouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedEtapa1Route: typeof AuthenticatedEtapa1Route
  AuthenticatedEtapa2Route: typeof AuthenticatedEtapa2Route
  AuthenticatedEtapa3Route: typeof AuthenticatedEtapa3Route
  AuthenticatedEtapa4Route: typeof AuthenticatedEtapa4Route
  AuthenticatedEtapa5Route: typeof AuthenticatedEtapa5Route
  AuthenticatedEtapa6Route: typeof AuthenticatedEtapa6Route
  AuthenticatedEtapa7Route: typeof AuthenticatedEtapa7Route
  AuthenticatedEtapa8Route: typeof AuthenticatedEtapa8Route
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedEtapa1Route: AuthenticatedEtapa1Route,
  AuthenticatedEtapa2Route: AuthenticatedEtapa2Route,
  AuthenticatedEtapa3Route: AuthenticatedEtapa3Route,
  AuthenticatedEtapa4Route: AuthenticatedEtapa4Route,
  AuthenticatedEtapa5Route: AuthenticatedEtapa5Route,
  AuthenticatedEtapa6Route: AuthenticatedEtapa6Route,
  AuthenticatedEtapa7Route: AuthenticatedEtapa7Route,
  AuthenticatedEtapa8Route: AuthenticatedEtapa8Route,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthCadastroRoute: AuthCadastroRoute,
  AuthEsqueciRoute: AuthEsqueciRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRedefinirRoute: AuthRedefinirRoute,
  AuthVerificacaoRoute: AuthVerificacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
